version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5442:5432"
    networks:
      - app_network

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8200:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "15344:80"
    networks:
      shared_network:
        external: true

networks:
  app_network:

volumes:
  postgres_data: