version: '3.8'

services:
  prbd-db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - prbd_postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5442:5432"
    networks:
      - app_network

  prbd-backend:
    build: ./backend
    depends_on:
      - prbd-db
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app_network
      - shared_network

  prbd-frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - shared_network

networks:
  app_network:
  shared_network:
    external: true

volumes:
  prbd_postgres_data: