services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    network_mode: host

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8200:8000"
    network_mode: host

  frontend:
    build: ./frontend
    ports:
      - "15344:80"
    network_mode: host